import type { CheckMetadata } from '@/services/checks';

const CHECK_ACTIONS: Record<string, string[]> = {
  ec2_idle_instances: [
    'Stop',
    'Terminate',
    'Terminate with snapshot',
    'Terminate but leave the volume',
  ],
  ec2_unused_instances: [
    'Terminate',
    'Terminate with snapshot',
    'Terminate but leave the volume',
  ],
  dynamodb_underutilized_tables: [
    'Delete table',
    'Backup and delete table',
    'Switch to On-Demand billing',
  ],
  dynamodb_underutilized_rcu: ['Reduce RCU', 'Enable autoscaling'],
  dynamodb_underutilized_wcu: ['Reduce WCU', 'Enable autoscaling'],
  dynamodb_best_fit_on_demand: ['Switch to On-Demand billing'],
  dynamodb_best_fit_provisioned: ['Use Provisioned Capacity', 'Enable autoscaling'],
  dynamodb_gsi_unused: ['Delete GSI'],
  elasticache_low_item_count: ['Downsize', 'Delete instance'],
  elasticache_redis_convertible_to_valkey: ['Upgrade to Valkey', 'Delete instance'],
  elasticache_non_graviton_instance_class: ['Migrate to Graviton node type'],
  s3_no_lifecycle_policy: ['Add lifecycle policy'],
  s3_no_mpu_policy: ['Add policy - Abort incomplete MPUs'],
  s3_no_noncurrent_expiration: ['Add policy - Expire noncurrent versions'],
  s3_no_expiration_policy: ['Add policy - Add expiration for old objects'],
  s3_no_archival_policy: ['Add policy - Add archival transition'],
  s3_no_delete_marker_expiration: ['Add policy - Enable delete-marker cleanup'],
  s3_inventory_enabled: ['Disable Inventory Report and delete the log bucket'],
  s3_logging_enabled: ['Disable Logging Report and delete the log bucket'],
  s3_replication_enabled: ['Disable replication and delete the replicate bucket'],
  s3_log_buckets_without_expiration_policy: ['Add policy - log retention lifecycle'],
  vpc_no_s3_vpc_endpoint: ['Create S3 Gateway Endpoint'],
  vpc_no_dynamodb_vpc_endpoint: ['Create DynamoDB Gateway Endpoint'],
  vpc_flow_logs_enabled: ['Disable flow logs and delete bucket'],
  cloudwatch_high_volume_alerts_triggered: ['Tune/dedupe noisy alarms'],
  cloudwatch_log_groups_high_ingest_bytes: ['Reduce log ingest'],
  cloudwatch_duplicate_alarms: ['Consolidate duplicates'],
  cloudwatch_log_groups_no_recent_ingestion: ['Reduce retention or delete'],
  glue_jobs_older_version: ['Upgrade GlueVersion'],
  ebs_unattached_volumes: ['Snapshot and Terminate', 'lifecycle policy'],
  ebs_underutilized_volume: ['Downsize volume'],
  ebs_iops_overprovisioned_volume: ['Reduce provisioned IOPS'],
  ebs_gp2_volumes_convertible_to_gp3: ['Modify volume type to gp3; tune IOPS/throughput'],
  ebs_underutilized_provisioned_iops: ['Reduce provisioned IOPS or migrate to gp3'],
  ebs_large_volumes_low_utilization: ['Downsize volume; consider filesystem resize + snapshot/restore'],
  rds_non_graviton_instance_class: ['Migrate to Graviton'],
  rds_idle_databases: ['Stop'],
  s3_no_noncurrent_version_transition: ['Add policy - Add noncurrent archival transition'],
  snapshot_old_snapshots: ['Delete snapshot'],
  efs_unused_file_systems: ['Delete file system'],
  efs_wrong_performance_mode: ['Modify performance mode'],
  efs_wrong_throughput_mode: ['Modify throughput mode'],
  efs_no_lifecycle_policy: ['Add lifecycle policy'],
  lambda_overprovisioned_memory: ['Rightsize memory using duration vs memory analysis'],
  lambda_provisioned_concurrency_low_usage: ['Reduce/disable provisioned concurrency'],
  lambda_high_log_ingestion: ['Reduce log verbosity; set retention'],
  ecs_services_desired_count_zero: ['Delete service; clean up ALB/TG/log groups/roles'],
  ecs_overprovisioned_task_cpu_memory_reservations: ['Rightsize task definition based on utilization'],
  sagemaker_endpoint_idle: ['Delete endpoint'],
  sagemaker_endpoint_overprovisioned: ['Reduce endpoint instance count'],
  sagemaker_endpoint_gpu_underutilized: ['Rightsize endpoint'],
  sagemaker_notebook_no_auto_stop: ['Attach auto-stop lifecycle config'],
  sagemaker_notebook_idle: ['Stop notebook', 'Attach auto-stop lifecycle config'],
  sagemaker_training_no_managed_spot: ['Enable managed spot training'],
  ecs_idle_clusters_no_active_services_tasks: ['Delete cluster after verifying no dependencies'],
};

export const getActionsForCheck = (check: CheckMetadata): string[] => {
  return CHECK_ACTIONS[check.check_id] || [];
};
